import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Overpass } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const overpass = Overpass({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Frontend Mentor | Interactive rating component",
    description: "Generated by create next app",
    viewport: {
        width: "device-width",
        initialScale: 1,
    },
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={overpass.className}>
            <body>{children}</body>
        </html>
    );
}
