import type { Metadata } from "next";
import { Overpass } from "next/font/google";
import "./globals.css";

const overpass = Overpass({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Frontend Mentor | Interactive rating component",
    description: "Generated by create next app",
    viewport: {
        width: "device-width",
        initialScale: 1,
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={overpass.className}>{children}</body>
        </html>
    );
}
