import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const overpass = localFont({
    src: "./fonts/Overpass-Regular.woff2",
    variable: "--font-overpass",
    weight: "400",
});
const overpassBold = localFont({
    src: "./fonts/Overpass-Bold.woff2",
    variable: "--font-overpass-bold",
    weight: "700",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${overpass.variable} ${overpassBold.variable}`}>
                {children}
            </body>
        </html>
    );
}
